# Render service definition for MeBooks proxy (moved to repo root so Render will detect it)
services:
  - type: web
    name: mebooks-proxy
    env: docker
    repo: JamesEnglish1028/JamesEnglish1028-My-Ebook-Reader
    branch: main
  dockerfilePath: Dockerfile
  dockerContext: .
    # plan can be 'free', 'starter', 'standard', etc. Pick in the Render UI; this is a placeholder.
    plan: free
    envVars:
      - key: HOST_ALLOWLIST
        value: opds.example,cdn.example
      - key: ALLOW_ORIGIN
        value: https://jamesenglish1028-my-ebook-reader.onrender.com
      # Do NOT include PROXY_KEY here; add it in Render dashboard as a secret for production
      # - key: PROXY_KEY
      #   value: "__SECRET__"
  healthCheckPath: /_health
    # No buildCommand: use Dockerfile at repo root
    startCommand: ''
