# Exported Render blueprint for MeBooks proxy
version: "1"
services:
- type: web
  name: JamesEnglish1028-My-Ebook-Reader
  runtime: docker
  repo: https://github.com/JamesEnglish1028/JamesEnglish1028-My-Ebook-Reader
  branch: main
  plan: free
  region: ohio
  healthCheckPath: /_health
  dockerContext: .
  dockerfilePath: proxy/Dockerfile
  autoDeployTrigger: commit
  envVars:
    - key: HOST_ALLOWLIST
      value: opds.example,cdn.example
    - key: ALLOW_ORIGIN
      value: https://jamesenglish1028-my-ebook-reader.onrender.com
  # (No temporary debug build command)
# Render service definition for MeBooks proxy (moved to repo root so Render will detect it)
services:
  - type: web
    name: mebooks-proxy
    env: docker
    repo: JamesEnglish1028/JamesEnglish1028-My-Ebook-Reader
    branch: main
    dockerfilePath: Dockerfile
    dockerContext: .
    # plan can be 'free', 'starter', 'standard', etc. Pick in the Render UI; this is a placeholder.
    plan: free
    envVars:
      - key: HOST_ALLOWLIST
        value: opds.example,cdn.example
      - key: ALLOW_ORIGIN
        value: https://jamesenglish1028-my-ebook-reader.onrender.com
      # Do NOT include PROXY_KEY here; add it in Render dashboard as a secret for production
      # - key: PROXY_KEY
      #   value: "__SECRET__"
    healthCheckPath: /_health
    # (Debug buildCommand removed now that build succeeds)
    startCommand: ''

- type: static
  name: mebooks-web
  repo: https://github.com/JamesEnglish1028/JamesEnglish1028-My-Ebook-Reader
  branch: main
  buildCommand: npm ci && npm run build
  publishPath: dist
  plan: free
  envVars:
    - key: VITE_OWN_PROXY_URL
      value: https://jamesenglish1028-my-ebook-reader.onrender.com
