[site]
bucket = "public"

[vars]
# Optionally set a PROXY_KEY in your Cloudflare Worker environment and pass it as x-proxy-key
# to protect the echo endpoint in production
# PROXY_KEY = "your-secret-key"

name = "mebooks-proxy-worker"
main = "./cloudflare-worker-example.js"
